# Hexo é…ç½®æ–‡ä»¶
nav:
  logo: https://github.com/YangRucheng.png
  display_title: true
  fixed: false # fixed navigation bar

# ç½‘ç«™
default_top_img: /static/images/é»˜è®¤èƒŒæ™¯.jpg
favicon: https://github.com/YangRucheng.png

# ç¤¾äº¤å›¾æ ‡
social:
  fab fa-github: https://github.com/YangRucheng/Blog-Hexo || Github
  fab fa-qq: https://qm.qq.com/q/rtZpWJIgPQ || QQ
  fab fa-bilibili: https://space.bilibili.com/472876342 || å“”å“©å“”å“©
  fas fa-envelope: mailto:admin@yangrucheng.top || Email

# å¤´åƒ
avatar:
  img: https://github.com/YangRucheng.png
  effect: true

# ä¾§è¾¹æ 
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: å…³æ³¨æˆ‘çš„GitHub
      link: https://github.com/YangRucheng
  card_announcement:
    enable: true
    content: æ¬¢è¿æ¥åˆ°æˆ‘çš„å°ç«™ğŸ‘ğŸ»

# èœå•
menu:
  é¦–é¡µ: / || fa fa-home
  æ—¶é—´è½´: /archives/ || fa fa-archive
  æ ‡ç­¾: /tags/ || fa fa-tags
  åˆ†ç±»: /categories/ || fa fa-folder-open
  å‹é“¾: /link/ || fa fa-link

# å³ä¸‹è§’æŒ‰é’®
darkmode:
  enable: true
  button: true
  autoChangeMode: 1
rightside_scroll_percent: true

# å°é¢
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover: https://api.anosu.top/img/?sort=furry

# è¯„è®º
comments:
  use: Giscus
  text: true
  lazyload: false
  count: true
  card_post_count: false

# Giscus https://giscus.app/
giscus:
  repo: YangRucheng/Blog-Hexo 
  repo_id: R_kgDOI4-j6Q
  category_id: DIC_kwDOI4-j6c4CUaSW
  theme:
    light: light
    dark: dark

# é¡µè„šå†…å®¹
footer:
  owner:
    enable: true
    since: 2025
  custom_text: <a href="https://beian.miit.gov.cn/#/Integrated/index"><span>æ¹˜ICPå¤‡2022020305å·</span></a> <a href="https://beian.mps.gov.cn/#/query/webSearch"><span>æ¹˜å…¬ç½‘å®‰å¤‡43040002000196å·</span></a>
  copyright: true

# è®¿é—®ç»Ÿè®¡
baidu_analytics: d63d156632659af16f30e3a10972c9b9
cloudflare_analytics: 591ae059fa6d429cb2c89f6d75491727
microsoft_clarity: s8xoxf658n
umami_analytics:
  enable: true
  serverURL: 
  website_id: 98a8a59e-4f66-47fe-bc7d-2fb8eba8ef51
  option:
  UV_PV:
    site_uv: true
    site_pv: true
    page_pv: true
    token: 
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true